WITH A AS (
    SELECT * 
    FROM ANIMAL_INS
    WHERE SEX_UPON_INTAKE LIKE 'Intact%'
)
SELECT A.ANIMAL_ID, A.ANIMAL_TYPE, A.NAME
FROM A LEFT JOIN ANIMAL_OUTS AS B
ON A.ANIMAL_ID = B.ANIMAL_ID
WHERE B.SEX_UPON_OUTCOME IN ('Spayed Female','Neutered Male')
;