-- 코드를 입력하세요
WITH MILK AS(
    SELECT DISTINCT CART_ID
    FROM CART_PRODUCTS
    WHERE NAME = 'Milk'
), Yogurt AS(
    SELECT DISTINCT CART_ID
    FROM CART_PRODUCTS
    WHERE NAME = 'Yogurt'
)

SELECT A.*
FROM MILK A JOIN Yogurt B
ON (A.CART_ID = B.CART_ID)
ORDER BY A.CART_ID ASC